# Generated by Django 5.1.5 on 2025-01-16 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='small_image',
            field=models.ImageField(default='about_images/default_small_image.jpg', upload_to='about_images/'),
        ),
    ]
