# Generated by Django 5.1.5 on 2025-01-16 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_aboutus_small_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
